#
# This file is autogenerated during plugin quickstart and overwritten during
# plugin makedist. DO NOT CHANGE IT if you plan to use plugin makedist to update 
# the distribution.
#

from setuptools import setup, find_packages

kwargs = {'author': 'Eric Hendricks',
 'author_email': 'eric.hendricks@nasa.gov',
 'classifiers': ['Intended Audience :: Science/Research',
                 'Topic :: Scientific/Engineering'],
 'description': 'OpenMDAO component wrapper for DREA',
 'download_url': '',
 'entry_points': '[openmdao.container]\ndrea_wrapper.geometry.Geometry=drea_wrapper.geometry:Geometry\ndrea_wrapper.stream.Stream=drea_wrapper.stream:Stream\ndrea_wrapper.MEflows.MEflows=drea_wrapper.MEflows:MEflows\ndrea_wrapper.DREA.DREA=drea_wrapper.DREA:DREA\n\n[openmdao.component]\ndrea_wrapper.DREA.DREA=drea_wrapper.DREA:DREA',
 'include_package_data': True,
 'install_requires': ['openmdao.main'],
 'keywords': ['openmdao'],
 'license': 'Apache License, Version 2.0',
 'maintainer': 'Kenneth Moore',
 'maintainer_email': 'kenneth.t.moore-1@nasa.gov',
 'name': 'drea_wrapper',
 'package_data': {'drea_wrapper': []},
 'package_dir': {'': 'src'},
 'packages': ['drea_wrapper'],
 'url': 'https://github.com/OpenMDAO-Plugins/drea_wrapper',
 'version': '0.1',
 'zip_safe': False}


setup(**kwargs)

